    CREATE TABLE users (
        ID SERIAL PRIMARY KEY,
        keycloak_id  VARCHAR(255) UNIQUE NOT NULL,
        username VARCHAR(255) NOT NULL
    );

    CREATE TABLE friends (
        FRIEND_1 INT NOT NULL,
        FRIEND_2 INT NOT NULL,
        FOREIGN KEY (FRIEND_1) REFERENCES users(ID),
        FOREIGN KEY (FRIEND_2) REFERENCES users(ID)
    );

    CREATE TABLE friends_requests (
        USER_ID INT NOT NULL,
        SENDER_ID INT NOT NULL,
        FOREIGN KEY (USER_ID) REFERENCES users(ID),
        FOREIGN KEY (SENDER_ID) REFERENCES users(ID)
    );



CREATE TABLE ankets (
        ID SERIAL PRIMARY KEY,
        USER_ID INT UNIQUE NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        AVATAR BOOLEAN DEFAULT FALSE,
        AGE INT,
        SEX BOOLEAN,
        SEX_FIND BOOLEAN,
        DESCRIPTION TEXT,
        LAT NUMERIC,
        LON NUMERIC,
        RATING INT,
        FOREIGN KEY (USER_ID) REFERENCES users(ID)
    )

    
CREATE TABLE chats_users (
    CHAT_ID SERIAL PRIMARY KEY,
    USER_1 INT NOT NULL,
    USER_2 INT NOT NULL,
    FOREIGN KEY (USER_1) REFERENCES users(ID),
    FOREIGN KEY (USER_2) REFERENCES users(ID)
)

CREATE TABLE chats (
    CHAT_ID INT NOT NULL,
    CHAT JSONB,
    FOREIGN KEY (CHAT_ID) REFERENCES chats_users(CHAT_ID)
);

CREATE TABLE media (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    NAME TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);

CREATE TABLE finance (
    USER_ID INT NOT NULL,
    BALANCE INT DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);
