CREATE TABLE IF NOT EXISTS users (
    ID SERIAL PRIMARY KEY,
    PASSPAIR VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    user_id VARCHAR(16) UNIQUE NOT NULL,
);

CREATE TABLE works (
    id SERIAL PRIMARY KEY,
    title TEXT,
    composer TEXT,
    sheet_url VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS friends (
    ID SERIAL PRIMARY KEY,
    FRIEND_1 INT NOT NULL,
    FRIEND_2 INT NOT NULL,
    FOREIGN KEY (FRIEND_1) REFERENCES users(ID),
    FOREIGN KEY (FRIEND_2) REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS friends_requests (
    USER_ID INT NOT NULL,
    SENDER_ID INT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID),
    FOREIGN KEY (SENDER_ID) REFERENCES users(ID)
);



CREATE TABLE IF NOT EXISTS ankets (
        ID SERIAL PRIMARY KEY,
        USER_ID INT UNIQUE NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        AVATAR VARCHAR(255) ,
        AGE INT,
        SEX BOOLEAN,
        SEX_FIND BOOLEAN,
        DESCRIPTION TEXT,
        LAT NUMERIC,
        LON NUMERIC,
        TELEGRAM VARCHAR(255),
        CITY VARCHAR(255),
        FOREIGN KEY (USER_ID) REFERENCES users(ID)
);
    

CREATE TABLE IF NOT EXISTS media (
    ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    NAME TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);


CREATE TABLE IF NOT EXISTS seen_users (
    user_id INTEGER,
    seen_user_id INTEGER,
    seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, seen_user_id)
);