CREATE TABLE finance (
    USER_ID INT NOT NULL,
    BALANCE INT DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);

CREATE TABLE gifts (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE INT NOT NULL,
    PRICE_SELL INT NOT NULL,
    IMAGE_PATH VARCHAR(255),
    IS_AVAILABEL BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS user_gifts (
    ID SERIAL PRIMARY KEY,
    OWNER_ID INT NOT NULL,
    GIFT_ID INT NOT NULL,
    SENDER_ID INT DEFAULT NULL,
    RECEIVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRICE INT NOT NULL,
    PRICE_SELL INT NOT NULL,
    SOLD BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (OWNER_ID) REFERENCES users(ID),
    FOREIGN KEY (SENDER_ID) REFERENCES users(ID),
    FOREIGN KEY (GIFT_ID) REFERENCES gifts(ID)
);CREATE TABLE chats_users (
    CHAT_ID SERIAL PRIMARY KEY,
    USER_1 INT NOT NULL,
    USER_2 INT NOT NULL,
    FOREIGN KEY (USER_1) REFERENCES users(ID),
    FOREIGN KEY (USER_2) REFERENCES users(ID)
)

CREATE TABLE chats (
    CHAT_ID INT NOT NULL,
    CHAT JSONB,
    FOREIGN KEY (CHAT_ID) REFERENCES chats_users(CHAT_ID)
);
